version: '3'

services:
    front:
        build: ./front
        restart: always
        ports:
        - "127.0.0.1:3000:80"
        container_name: nocco_front
    back:
        restart: always
        build: ./back
        command: poetry run python app.py
        ports:
        - "127.0.0.1:8000:8000"
        container_name: nocco_back
        environment:
        -  ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
        networks: #here
            - my-network 
    mongodb:
        container_name: nocco_mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        ports:
        - 27017:27017
        networks: #here
            - my-network 
networks:
    my-network:
        driver: bridge
volumes:
   mongodbdata:
      driver: local